apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-specific-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-info
  template:
    metadata:
      labels:
        app: node-info
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: custom-label
                    operator: In
                    values:
                      - "pepi-master"  # Ensure the node has this label to schedule the pod
      containers:
        - name: name-node-container
          image: pepi1989/client_pod:v162  # Replace this with your correct image
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # Dynamically gets pod name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace  # Dynamically gets pod namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName  # Dynamically gets the node name where the pod is running
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"  # Prometheus service URL
