apiVersion: v1
kind: Service
metadata:
  name: scale-service
spec:
  selector:
    app: scale_pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer  # You can use NodePort if you prefer
