apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1  # Set the replica count
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      serviceAccountName: default  # The service account (to be used with Role/RoleBinding)
      containers:
      - name: fastapi
        image: pepi1989/scale-pod:v14  # The Docker image name (replace this with your actual image)
        ports:
        - containerPort: 8001
          protocol: TCP
