apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Role
metadata:
  namespace: default  # The namespace where FastAPI app operates
  name: fastapi-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]  # Allow patching scale resources
    verbs: ["patch"]  # Specifically grant permission to patch deployments/scale