apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-deployment
  labels:
    app: scale_pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale_pod
  template:
    metadata:
      labels:
        app: scale_pod
    spec:
      containers:
        - name: scale-pod-container
          image: pepi1989/scale-pod:v11  # Replace with your Docker image
          ports:
            - containerPort: 8001
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
