apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # RoleBinding
metadata:
  name: fastapi-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default  # Using the default service account
  namespace: default
roleRef:
  kind: ClusterRole
  name: fastapi-role  # The Role we created above
  apiGroup: rbac.authorization.k8s.io



