apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Role
metadata:
  namespace: default  # The namespace where FastAPI app operates
  name: fastapi-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
