apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80  # The external port
      targetPort: 8001  # The internal FastAPI port
  type: NodePort  # Exposes the service on a random NodePort
