apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-specific-app
spec:
  selector:
    matchLabels:
      app: node-info
  template:
    metadata:
      labels:
        app: node-info
    spec:
      serviceAccountName: agent-sa  # 🔹 Ensures correct permissions
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: custom-label
                    operator: In
                    values:
                      - "worker-1"
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 2Gi  # 🔹 Temporary storage limited to 2Gi
      containers:
        - name: name-node-container
          image: pepi1989/client_pod:v203
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"  # Increase from 500m (0.5 CPU) to 1 full CPU
              memory: "2Gi"  # Increase from 1Gi to 2Gi
              ephemeral-storage: "4Gi"  # Increase from 2Gi to 4Gi
            limits:
              cpu: "4"  # Increase from 2 CPUs to 4
              memory: "8Gi"  # Increase from 4Gi to 8Gi
              ephemeral-storage: "10Gi"  # Increase from 5Gi to 10Gi
          volumeMounts:
            - mountPath: "/cache"
              name: cache-volume  # 🔹 Mount emptyDir as cache
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
            - name: FEDERATION_URL_SEND
              value: "http://fed-master-service:8002/upload_weights_fdl_master"
            - name: FEDERATION_URL_RECEIVE
              value: "http://eceive-fed-weights-service:8001/get_aggregated_json_weights"
