apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sa  # New service account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: agent-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]  # Now includes daemonsets
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]  # Allow patching scale resources
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: agent-sa  # Use the new dedicated service account
  namespace: default
roleRef:
  kind: ClusterRole
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
