apiVersion: v1
kind: ServiceAccount
metadata:
  name: publication-data-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: publication-data-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: publication-data-rolebinding
subjects:
- kind: ServiceAccount
  name: publication-data-sa  # ✅ Correct service account here
  namespace: default
roleRef:
  kind: ClusterRole
  name: publication-data-role  # ✅ Reference to the correct ClusterRole
  apiGroup: rbac.authorization.k8s.io
