# Create a ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-app-sa

---
# Create a Role for viewing nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-viewer
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---
# Create a RoleBinding to bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-viewer-binding
roleRef:
  name: node-viewer
  kind: Role
subjects:
- kind: ServiceAccount
  name: fastapi-sa
  namespace: default

---
# Create a ClusterRole for accessing Prometheus metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-access
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

---
# Create a ClusterRoleBinding to bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-access-binding
roleRef:
  name: prometheus-access
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: cpu-app-sa
  namespace: default
