# Create a Role for viewing nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-viewer
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---
# Create a RoleBinding to bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-viewer-binding
roleRef:
  name: node-viewer
  kind: Role
subjects:
- kind: ServiceAccount
  name: cpu-app-sa
  namespace: default
