apiVersion: v1
kind: Pod
metadata:
  name: load-simulator
spec:
  hostNetwork: true
  containers:
  - name: load
    image: pepi1989/load-simulator:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    resources:
      limits:
        cpu: "2"
        memory: "1Gi"
