apiVersion: v1
kind: Service
metadata:
  name: eceive-fed-weights-service
spec:
  selector:
    app: eceive-fed-weights-receive
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  clusterIP: None  # This is for headless service (useful for communication between pods)
