apiVersion: v1
kind: Service
metadata:
  name: receive-fed-weights-service
spec:
  selector:
    app: receive-fed-weights-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  clusterIP: None  # This is for headless service (useful for communication between pods)
