apiVersion: v1
kind: Service
metadata:
  name: receive-fed-weights-service
spec:
  selector:
    app: receive-fed-weights  # FIX: Must match the Deployment label
  ports:
    - protocol: TCP
      port: 8001  # External service port
      targetPort: 8001  # Matches containerPort in Deployment
  type: ClusterIP  # Default type (removing `clusterIP: None` unless needed)

