apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-aggregation-weights
  labels:
    app: master-aggregation-weights
spec:
  replicas: 1  # Number of replicas for scaling
  selector:
    matchLabels:
      app: master-aggregation-weights  # Ensure labels match with the template
  template:
    metadata:
      labels:
        app: master-aggregation-weights  # Ensure labels match with the selector
    spec:
      nodeSelector:
        custom-label: pepi-master  # Matches the label on pepi-master
      volumes:
        - name: node-notebook
          persistentVolumeClaim:
            claimName: node-notebook-pvc
        - name: master-weights
          persistentVolumeClaim:
            claimName: master-weights-pvc  # Make sure this PVC exists
        - name: aggregated-json-files
          persistentVolumeClaim:
            claimName: aggregated-json-file-pvc  # Make sure this PVC exists
        - name: federated-send-results
          persistentVolumeClaim:
            claimName: federated-send-results-pvc  # Make sure this PVC exists
      containers:
        - name: master-weights-aggregation
          image: pepi1989/master-aggregation-weights:v1  # Replace with your Docker image name
          volumeMounts:
            - mountPath: /app/nodes_notebook
              name: node-notebook
            - mountPath: /app/master_received_weights_json  # Absolute path in the container
              name: master-weights
            - mountPath: /app/aggregated_json_files
              name: aggregated-json-files
            - mountPath: /app/federated_send_results  # Corrected key from `mountpath`
              name: federated-send-results


