apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cpu-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - path: /api/cpu_latency
        pathType: Prefix
        backend:
          service:
            name: cpu-app-service
            port:
              number: 80
