apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
spec:
  http:
  - paths:
    - path: /api/cpu_latency
      pathType: Prefix
      backend:
        service:
          name: fastapi-service
          port:
            number: 80
